11#!/usr/bin/env python3
"""
Generate downloader.sh script to download works from multiple sources asynchronously
"""

import os
import yaml
import subprocess
from pathlib import Path

# Load configuration relative to this script
script_dir = os.path.dirname(os.path.abspath(__file__))
config_path = os.path.join(script_dir, 'data.yaml')

with open(config_path) as f:
    config = yaml.safe_load(f)

def download_single_source(source_id, output_dir):
    """Download works for a single source using openalex CLI"""
    print(f"Downloading works for source: {source_id}")
    
    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    cmd = [
        "openalex", "download",
        f"--filter=publication_year:>1999,primary_location.source.id:{source_id}",
        "--nested",
        "--fresh",
        "--quiet",
        f"--output={output_dir}"
    ]
    
    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        print(f"Error: {result.stderr}")
        return False
    
    print(f"Download completed. Output: {result.stdout}")
    return True

def generate_downloader_script(sources_file, output_script, json_base_dir):
    """Generate bash script to download from all sources in parallel"""
    
    # Read sources
    with open(sources_file, 'r') as f:
        sources = [line.strip() for line in f if line.strip()]
    
    print(f"Found {len(sources)} sources in {sources_file}")
    
    # Generate bash script
    script_content = f"""#!/bin/bash
# Auto-generated downloader script for OpenAlex economics/business sources
# Generated by downloader.py on {os.system('date')}

set -e  # Exit on error

BASE_DIR="{json_base_dir}"
LOG_DIR="$BASE_DIR/logs"

# Create directories
mkdir -p "$BASE_DIR"
mkdir -p "$LOG_DIR"

echo "Starting downloads for {len(sources)} sources..."
echo "Base directory: $BASE_DIR"
echo "Logs directory: $LOG_DIR"

# Function to download a single source
download_source() {{
    local source_id="$1"
    local source_name=$(basename "$source_id")
    local output_dir="$BASE_DIR/$source_name"
    local log_file="$LOG_DIR/$source_name.log"
    
    echo "[$source_name] Starting download..." | tee -a "$log_file"
    
    # Create source-specific directory
    mkdir -p "$output_dir"
    
    # Download with openalex CLI
    openalex download \\
        --filter="publication_year:>1999,primary_location.source.id:$source_id" \\
        --nested \\
        --fresh \\
        --quiet \\
        --output="$output_dir" \\
        2>&1 | tee -a "$log_file"
    
    if [ $? -eq 0 ]; then
        echo "[$source_name] ✓ Completed successfully" | tee -a "$log_file"
    else
        echo "[$source_name] ✗ Failed" | tee -a "$log_file"
    fi
}}

# Export function for parallel execution
export -f download_source

# Download sources in parallel (adjust -j value based on your system)
echo "Downloading sources in parallel..."
printf '%s\\n' \\
"""
    
    # Add each source to the script
    for i, source in enumerate(sources):
        script_content += f'    "{source}"'
        if i < len(sources) - 1:
            script_content += " \\\n"
        else:
            script_content += "\n"
    
    # Complete the script
    script_content += f"""
# Run downloads in parallel (max 4 concurrent jobs)
printf '%s\\n' \\
"""
    
    for i, source in enumerate(sources):
        script_content += f'    "{source}"'
        if i < len(sources) - 1:
            script_content += " \\\n"
        else:
            script_content += " | \\\n"
    
    script_content += """xargs -I {} -P 4 bash -c 'download_source "$@"' _ {}

echo "All downloads completed!"
echo "Check logs in: $LOG_DIR"

# Summary
echo ""
echo "=== DOWNLOAD SUMMARY ==="
success_count=$(grep -l "✓ Completed successfully" "$LOG_DIR"/*.log | wc -l)
total_count=$(ls "$LOG_DIR"/*.log 2>/dev/null | wc -l)
echo "Successful downloads: $success_count / $total_count"

if [ $success_count -lt $total_count ]; then
    echo ""
    echo "Failed downloads:"
    grep -l "✗ Failed" "$LOG_DIR"/*.log | sed 's/.*\///' | sed 's/\.log$//'
fi
"""
    
    # Write script to file
    with open(output_script, 'w') as f:
        f.write(script_content)
    
    # Make executable
    os.chmod(output_script, 0o755)
    
    print(f"Generated downloader script: {output_script}")
    print(f"To run: ./{output_script}")
    print(f"Sources will be downloaded to: {json_base_dir}")
    
    return True

def create_test_sources_subset(sources_file, test_file, count=10):
    """Create a smaller subset of sources for testing"""
    with open(sources_file, 'r') as f:
        sources = [line.strip() for line in f if line.strip()]
    
    # Take first `count` sources for testing
    test_sources = sources[:count]
    
    with open(test_file, 'w') as f:
        for source in test_sources:
            f.write(f"{source}\n")
    
    print(f"Created test sources file: {test_file}")
    print(f"Contains {len(test_sources)} sources for testing")
    
    return test_file

if __name__ == "__main__":
    # Paths
    sources_file = os.path.join(script_dir, 'aarchive', 'sources.txt')
    output_script = os.path.join(script_dir, 'downloader.sh')
    
    # Use config for base JSON directory, but organize by source
    json_base_dir = config['WORKING_DIR'] + '/json_sources'
    
    # Create test subset first (for development)
    test_sources_file = os.path.join(script_dir, 'test_sources.txt')
    create_test_sources_subset(sources_file, test_sources_file, count=10)
    
    print("\n=== Choose download option ===")
    print("1. Generate script for TEST sources (10 journals)")
    print("2. Generate script for ALL sources (600+ journals)")
    
    choice = input("Enter choice [1/2]: ").strip()
    
    if choice == "2":
        print("\\nGenerating downloader for ALL sources...")
        generate_downloader_script(sources_file, output_script, json_base_dir)
    else:
        print("\\nGenerating downloader for TEST sources...")
        test_script = os.path.join(script_dir, 'test_downloader.sh')
        generate_downloader_script(test_sources_file, test_script, json_base_dir + '_test')
        print(f"\\nTest script created: {test_script}")
        print("Run this first to test the pipeline before downloading all sources")