#!/bin/bash
# Auto-generated downloader script for OpenAlex economics/business sources
# Generated by downloader.py on 0

set -e  # Exit on error

BASE_DIR="/home/lc/m/working/econ_bus/json_sources_test"
LOG_DIR="$BASE_DIR/logs"

# Create directories
mkdir -p "$BASE_DIR"
mkdir -p "$LOG_DIR"

echo "Starting downloads for 10 sources..."
echo "Base directory: $BASE_DIR"
echo "Logs directory: $LOG_DIR"

# Function to download a single source
download_source() {
    local source_id="$1"
    local source_name=$(basename "$source_id")
    local output_dir="$BASE_DIR/$source_name"
    local log_file="$LOG_DIR/$source_name.log"
    
    echo "[$source_name] Starting download..." | tee -a "$log_file"
    
    # Create source-specific directory
    mkdir -p "$output_dir"
    
    # Download with openalex CLI
    openalex download \
        --filter="publication_year:>1999,primary_location.source.id:$source_id" \
        --nested \
        --fresh \
        --quiet \
        --output="$output_dir" \
        2>&1 | tee -a "$log_file"
    
    if [ $? -eq 0 ]; then
        echo "[$source_name] ✓ Completed successfully" | tee -a "$log_file"
    else
        echo "[$source_name] ✗ Failed" | tee -a "$log_file"
    fi
}

# Export function for parallel execution
export -f download_source

# Download sources in parallel (adjust -j value based on your system)
echo "Downloading sources in parallel..."
printf '%s\n' \
    "https://openalex.org/S100134864" \
    "https://openalex.org/S100149336" \
    "https://openalex.org/S100711025" \
    "https://openalex.org/S101163346" \
    "https://openalex.org/S101209419" \
    "https://openalex.org/S1014724869" \
    "https://openalex.org/S1027187413" \
    "https://openalex.org/S102805530" \
    "https://openalex.org/S102949365" \
    "https://openalex.org/S103311983"

# Run downloads in parallel (max 4 concurrent jobs)
printf '%s\n' \
    "https://openalex.org/S100134864" \
    "https://openalex.org/S100149336" \
    "https://openalex.org/S100711025" \
    "https://openalex.org/S101163346" \
    "https://openalex.org/S101209419" \
    "https://openalex.org/S1014724869" \
    "https://openalex.org/S1027187413" \
    "https://openalex.org/S102805530" \
    "https://openalex.org/S102949365" \
    "https://openalex.org/S103311983" | \
xargs -I {} -P 4 bash -c 'download_source "$@"' _ {}

echo "All downloads completed!"
echo "Check logs in: $LOG_DIR"

# Summary
echo ""
echo "=== DOWNLOAD SUMMARY ==="
success_count=$(grep -l "✓ Completed successfully" "$LOG_DIR"/*.log | wc -l)
total_count=$(ls "$LOG_DIR"/*.log 2>/dev/null | wc -l)
echo "Successful downloads: $success_count / $total_count"

if [ $success_count -lt $total_count ]; then
    echo ""
    echo "Failed downloads:"
    grep -l "✗ Failed" "$LOG_DIR"/*.log | sed 's/.*\///' | sed 's/\.log$//'
fi
